name: RTL Migration
on:
  push:
    branches:
      - 'check_workflow'
    paths:
      - '**.spec.tsx'

jobs:
    enzyme-rtl-migration:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: ./.github/actions/npm-cache/
        - run: npm run measure-enzyme-to-rtl
          env:
            SHEET_DB_TOKEN: ${{ secrets.SHEET_DB_TOKEN }}
